name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_ENV: production

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build project
      run: npm run build
      
    - name: Run tests
      run: npm test
      
    - name: Use environment variable
      run: echo "Node environment: $NODE_ENV"
      
    - name: Conditional step
      if: github.event_name == 'push'
      run: echo "This step only runs on push events"
      
    - name: Set output
      id: set-output
      run: echo "build_status=success" >> $GITHUB_OUTPUT
      
    - name: Use output
      run: echo "Build status: ${{ steps.set-output.outputs.build_status }}"

    - name: Use secret
      run: echo "API token is: ${{ secrets.API_TOKEN }}"
      if: github.event_name == 'push'